%YAML 1.2
---
public_folder: public
services:
  check_is_winning:
    description: use this service to check out your belief about a certain configuration to be a winning one.
    evaluator: [python, services/check_val_server.py]
    args:
      m:
        regex: ^([1-9][0-9]{0,50})$
        default: 1
        explain: Number of rows of the chocolate bar.
      n:
        regex: ^([1-9][0-9]{0,50})$
        default: 1
        explain: Number of columns of the chocolate bar.
      value:
        regex: ^0$
        default: 0
        explain: Your bet is that the (m,n) configuration is a winning one.
      info_requested:
        regex: ^just_check_my_conjecture$
        default: just_check_my_conjecture
      silent:
        regex: ^(0|1)$
        default: 0
        explain: If this flag is set to 1 then nothing is printed unless your conjecture is a false one.
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  check_is_lost:
    description: use this service to check out your belief about a certain configuration to be a lost one.
    evaluator: [python, services/check_val_server.py]
    args:
      m:
        regex: ^([1-9][0-9]{0,50})$
        default: 1
        explain: Number of rows of the chocolate bar.
      n:
        regex: ^([1-9][0-9]{0,50})$
        default: 1
        explain: Number of columns of the chocolate bar.
      value:
        regex: ^-1$
        default: -1
        explain: Your bet is that the (m,n) configuration is a lost one.
      info_requested:
        regex: ^just_check_my_conjecture$
        default: just_check_my_conjecture
      silent:
        regex: ^(0|1)$
        default: 0
        explain: If this flag is set to 1 then nothing is printed unless your conjecture is a false one.
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  check_grundy_value:
    evaluator: [python, services/check_val_server.py]
    args:
      m:
        regex: ^([1-9][0-9]{0,50})$
        default: 1
        explain: Number of rows of the chocolate bar.
      n:
        regex: ^([1-9][0-9]{0,50})$
        default: 1
        explain: Number of columns of the chocolate bar.
      info_requested:
        regex: ^just_check_my_conjecture$
        default: just_check_my_conjecture
      value:
        regex: ^(0|[1-9][0-9]{0,50})$
        default: 0
        explain: The grundy value that you are guessing for a chocolate bar of m rows and n columns.
      silent:
        regex: ^(0|1)$
        default: 0
        explain: If this flag is set to 1 then nothing is printed unless your conjecture is a false one.
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  tell_me_about_config:
    evaluator: [python, services/check_val_server.py]
    args:
      m:
        regex: ^([1-9][0-9]{0,50})$
        default: 1
        explain: Number of rows of the chocolate bar.
      n:
        regex: ^([1-9][0-9]{0,50})$
        default: 1
        explain: Number of columns of the chocolate bar.
      info_requested:
        regex: ^(won_or_lost|grundy_val)$
        default: won_or_lost
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it

  synopsis:
    evaluator: [python, services/synopsis/synopsis_server.py]
    args:
      service:
        regex: ^((\S)+)$
        default: synopsis
        explain: any string without space characters but meant to specify one of the services of the problem {problem}
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
...
